/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AbstractReferenceDataDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class AbstractReferenceDataDtoBase extends AbstractDto {

        private var _code:String;
        private var _description:String;
        private var _longName:String;
        private var _ref:String;
        private var _shortName:String;

        public function set code(value:String):void {
            _code = value;
        }
        public function get code():String {
            return _code;
        }

        public function set description(value:String):void {
            _description = value;
        }
        public function get description():String {
            return _description;
        }

        public function set longName(value:String):void {
            _longName = value;
        }
        public function get longName():String {
            return _longName;
        }

        public function set ref(value:String):void {
            _ref = value;
        }
        public function get ref():String {
            return _ref;
        }

        public function set shortName(value:String):void {
            _shortName = value;
        }
        public function get shortName():String {
            return _shortName;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _code = input.readObject() as String;
            _description = input.readObject() as String;
            _longName = input.readObject() as String;
            _ref = input.readObject() as String;
            _shortName = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_code);
            output.writeObject(_description);
            output.writeObject(_longName);
            output.writeObject(_ref);
            output.writeObject(_shortName);
        }
    }
}