/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AddressDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class AddressDtoBase extends AbstractDto {

        private var _address1:String;
        private var _address2:String;
        private var _city:String;
        private var _cityName:String;
        private var _state:String;
        private var _type:String;
        private var _zip:String;

        public function set address1(value:String):void {
            _address1 = value;
        }
        public function get address1():String {
            return _address1;
        }

        public function set address2(value:String):void {
            _address2 = value;
        }
        public function get address2():String {
            return _address2;
        }

        public function set city(value:String):void {
            _city = value;
        }
        public function get city():String {
            return _city;
        }

        public function set cityName(value:String):void {
            _cityName = value;
        }
        public function get cityName():String {
            return _cityName;
        }

        public function set state(value:String):void {
            _state = value;
        }
        public function get state():String {
            return _state;
        }

        public function set type(value:String):void {
            _type = value;
        }
        public function get type():String {
            return _type;
        }

        public function set zip(value:String):void {
            _zip = value;
        }
        public function get zip():String {
            return _zip;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _address1 = input.readObject() as String;
            _address2 = input.readObject() as String;
            _city = input.readObject() as String;
            _cityName = input.readObject() as String;
            _state = input.readObject() as String;
            _type = input.readObject() as String;
            _zip = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_address1);
            output.writeObject(_address2);
            output.writeObject(_city);
            output.writeObject(_cityName);
            output.writeObject(_state);
            output.writeObject(_type);
            output.writeObject(_zip);
        }
    }
}