/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AffiliationDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class AffiliationDtoBase extends AbstractDto {

        private var _history:String;
        private var _organization:String;
        private var _role:String;

        public function set history(value:String):void {
            _history = value;
        }
        public function get history():String {
            return _history;
        }

        public function set organization(value:String):void {
            _organization = value;
        }
        public function get organization():String {
            return _organization;
        }

        public function set role(value:String):void {
            _role = value;
        }
        public function get role():String {
            return _role;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _history = input.readObject() as String;
            _organization = input.readObject() as String;
            _role = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_history);
            output.writeObject(_organization);
            output.writeObject(_role);
        }
    }
}