/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AwardDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class AwardDtoBase extends AbstractDto {

        private var _awardName:String;
        private var _biography:String;
        private var _issuedDate:Date;
        private var _issuer:String;

        public function set awardName(value:String):void {
            _awardName = value;
        }
        public function get awardName():String {
            return _awardName;
        }

        public function set biography(value:String):void {
            _biography = value;
        }
        public function get biography():String {
            return _biography;
        }

        public function set issuedDate(value:Date):void {
            _issuedDate = value;
        }
        public function get issuedDate():Date {
            return _issuedDate;
        }

        public function set issuer(value:String):void {
            _issuer = value;
        }
        public function get issuer():String {
            return _issuer;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _awardName = input.readObject() as String;
            _biography = input.readObject() as String;
            _issuedDate = input.readObject() as Date;
            _issuer = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_awardName);
            output.writeObject(_biography);
            output.writeObject(_issuedDate);
            output.writeObject(_issuer);
        }
    }
}