/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (BiographyDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class BiographyDtoBase extends AbstractDto {

        private var _awards:ListCollectionView;
        private var _biographyCities:ListCollectionView;
        private var _biographyDepartments:ListCollectionView;
        private var _biographySkilledRoles:ListCollectionView;
        private var _biographySkills:ListCollectionView;
        private var _patents:ListCollectionView;
        private var _person:String;
        private var _publications:ListCollectionView;
        private var _summary:String;

        public function set awards(value:ListCollectionView):void {
            _awards = value;
        }
        public function get awards():ListCollectionView {
            return _awards;
        }

        public function set biographyCities(value:ListCollectionView):void {
            _biographyCities = value;
        }
        public function get biographyCities():ListCollectionView {
            return _biographyCities;
        }

        public function set biographyDepartments(value:ListCollectionView):void {
            _biographyDepartments = value;
        }
        public function get biographyDepartments():ListCollectionView {
            return _biographyDepartments;
        }

        public function set biographySkilledRoles(value:ListCollectionView):void {
            _biographySkilledRoles = value;
        }
        public function get biographySkilledRoles():ListCollectionView {
            return _biographySkilledRoles;
        }

        public function set biographySkills(value:ListCollectionView):void {
            _biographySkills = value;
        }
        public function get biographySkills():ListCollectionView {
            return _biographySkills;
        }

        public function set patents(value:ListCollectionView):void {
            _patents = value;
        }
        public function get patents():ListCollectionView {
            return _patents;
        }

        public function set person(value:String):void {
            _person = value;
        }
        public function get person():String {
            return _person;
        }

        public function set publications(value:ListCollectionView):void {
            _publications = value;
        }
        public function get publications():ListCollectionView {
            return _publications;
        }

        public function set summary(value:String):void {
            _summary = value;
        }
        public function get summary():String {
            return _summary;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _awards = input.readObject() as ListCollectionView;
            _biographyCities = input.readObject() as ListCollectionView;
            _biographyDepartments = input.readObject() as ListCollectionView;
            _biographySkilledRoles = input.readObject() as ListCollectionView;
            _biographySkills = input.readObject() as ListCollectionView;
            _patents = input.readObject() as ListCollectionView;
            _person = input.readObject() as String;
            _publications = input.readObject() as ListCollectionView;
            _summary = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_awards);
            output.writeObject(_biographyCities);
            output.writeObject(_biographyDepartments);
            output.writeObject(_biographySkilledRoles);
            output.writeObject(_biographySkills);
            output.writeObject(_patents);
            output.writeObject(_person);
            output.writeObject(_publications);
            output.writeObject(_summary);
        }
    }
}