/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CityDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class CityDtoBase extends AbstractReferenceDataDto {

        private var _country:String;

        public function set country(value:String):void {
            _country = value;
        }
        public function get country():String {
            return _country;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _country = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_country);
        }
    }
}