/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CompanyTitleDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class CompanyTitleDtoBase extends AbstractDto {

        private var _company:String;
        private var _companyName:String;
        private var _rating:Number;
        private var _title:String;
        private var _titleName:String;

        public function set company(value:String):void {
            _company = value;
        }
        public function get company():String {
            return _company;
        }

        public function set companyName(value:String):void {
            _companyName = value;
        }
        public function get companyName():String {
            return _companyName;
        }

        public function set rating(value:Number):void {
            _rating = value;
        }
        public function get rating():Number {
            return _rating;
        }

        public function set title(value:String):void {
            _title = value;
        }
        public function get title():String {
            return _title;
        }

        public function set titleName(value:String):void {
            _titleName = value;
        }
        public function get titleName():String {
            return _titleName;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _company = input.readObject() as String;
            _companyName = input.readObject() as String;
            _rating = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _title = input.readObject() as String;
            _titleName = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_company);
            output.writeObject(_companyName);
            output.writeObject(_rating);
            output.writeObject(_title);
            output.writeObject(_titleName);
        }
    }
}