/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CompanyDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class CompanyDtoBase extends AbstractReferenceDataDto {

        private var _contactName:String;
        private var _contactPhone:String;
        private var _parent:String;

        public function set contactName(value:String):void {
            _contactName = value;
        }
        public function get contactName():String {
            return _contactName;
        }

        public function set contactPhone(value:String):void {
            _contactPhone = value;
        }
        public function get contactPhone():String {
            return _contactPhone;
        }

        public function set parent(value:String):void {
            _parent = value;
        }
        public function get parent():String {
            return _parent;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _contactName = input.readObject() as String;
            _contactPhone = input.readObject() as String;
            _parent = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_contactName);
            output.writeObject(_contactPhone);
            output.writeObject(_parent);
        }
    }
}