/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CoverageEndorsementDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class CoverageEndorsementDtoBase extends AbstractDto {

        private var _coverage:String;
        private var _endorsement:EndorsementDto;

        public function set coverage(value:String):void {
            _coverage = value;
        }
        public function get coverage():String {
            return _coverage;
        }

        public function set endorsement(value:EndorsementDto):void {
            _endorsement = value;
        }
        public function get endorsement():EndorsementDto {
            return _endorsement;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _coverage = input.readObject() as String;
            _endorsement = input.readObject() as EndorsementDto;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_coverage);
            output.writeObject(_endorsement);
        }
    }
}