/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (CoverageDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class CoverageDtoBase extends AbstractDto {

        private var _company:CompanyDto;
        private var _coverageEndorsements:ListCollectionView;
        private var _history:String;
        private var _product:ProductDto;
        private var _region:RegionDto;
        private var _skilledRole:SkilledRoleDto;

        public function set company(value:CompanyDto):void {
            _company = value;
        }
        public function get company():CompanyDto {
            return _company;
        }

        public function set coverageEndorsements(value:ListCollectionView):void {
            _coverageEndorsements = value;
        }
        public function get coverageEndorsements():ListCollectionView {
            return _coverageEndorsements;
        }

        public function set history(value:String):void {
            _history = value;
        }
        public function get history():String {
            return _history;
        }

        public function set product(value:ProductDto):void {
            _product = value;
        }
        public function get product():ProductDto {
            return _product;
        }

        public function set region(value:RegionDto):void {
            _region = value;
        }
        public function get region():RegionDto {
            return _region;
        }

        public function set skilledRole(value:SkilledRoleDto):void {
            _skilledRole = value;
        }
        public function get skilledRole():SkilledRoleDto {
            return _skilledRole;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _company = input.readObject() as CompanyDto;
            _coverageEndorsements = input.readObject() as ListCollectionView;
            _history = input.readObject() as String;
            _product = input.readObject() as ProductDto;
            _region = input.readObject() as RegionDto;
            _skilledRole = input.readObject() as SkilledRoleDto;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_company);
            output.writeObject(_coverageEndorsements);
            output.writeObject(_history);
            output.writeObject(_product);
            output.writeObject(_region);
            output.writeObject(_skilledRole);
        }
    }
}