/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DegreeDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class DegreeDtoBase extends AbstractDto {

        private var _completedDate:Date;
        private var _education:String;
        private var _major:String;
        private var _school:String;
        private var _schoolName:String;
        private var _type:String;

        public function set completedDate(value:Date):void {
            _completedDate = value;
        }
        public function get completedDate():Date {
            return _completedDate;
        }

        public function set education(value:String):void {
            _education = value;
        }
        public function get education():String {
            return _education;
        }

        public function set major(value:String):void {
            _major = value;
        }
        public function get major():String {
            return _major;
        }

        public function set school(value:String):void {
            _school = value;
        }
        public function get school():String {
            return _school;
        }

        public function set schoolName(value:String):void {
            _schoolName = value;
        }
        public function get schoolName():String {
            return _schoolName;
        }

        public function set type(value:String):void {
            _type = value;
        }
        public function get type():String {
            return _type;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _completedDate = input.readObject() as Date;
            _education = input.readObject() as String;
            _major = input.readObject() as String;
            _school = input.readObject() as String;
            _schoolName = input.readObject() as String;
            _type = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_completedDate);
            output.writeObject(_education);
            output.writeObject(_major);
            output.writeObject(_school);
            output.writeObject(_schoolName);
            output.writeObject(_type);
        }
    }
}