/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (EducationCertificationDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class EducationCertificationDtoBase extends AbstractDto {

        private var _certification:CertificationDto;
        private var _education:String;
        private var _issueDate:Date;
        private var _issuedBy:String;
        private var _title:String;

        public function set certification(value:CertificationDto):void {
            _certification = value;
        }
        public function get certification():CertificationDto {
            return _certification;
        }

        public function set education(value:String):void {
            _education = value;
        }
        public function get education():String {
            return _education;
        }

        public function set issueDate(value:Date):void {
            _issueDate = value;
        }
        public function get issueDate():Date {
            return _issueDate;
        }

        public function set issuedBy(value:String):void {
            _issuedBy = value;
        }
        public function get issuedBy():String {
            return _issuedBy;
        }

        public function set title(value:String):void {
            _title = value;
        }
        public function get title():String {
            return _title;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _certification = input.readObject() as CertificationDto;
            _education = input.readObject() as String;
            _issueDate = input.readObject() as Date;
            _issuedBy = input.readObject() as String;
            _title = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_certification);
            output.writeObject(_education);
            output.writeObject(_issueDate);
            output.writeObject(_issuedBy);
            output.writeObject(_title);
        }
    }
}