/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (EducationDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class EducationDtoBase extends AbstractDto {

        private var _degrees:ListCollectionView;
        private var _educationCertifications:ListCollectionView;
        private var _languages:ListCollectionView;
        private var _person:String;

        public function set degrees(value:ListCollectionView):void {
            _degrees = value;
        }
        public function get degrees():ListCollectionView {
            return _degrees;
        }

        public function set educationCertifications(value:ListCollectionView):void {
            _educationCertifications = value;
        }
        public function get educationCertifications():ListCollectionView {
            return _educationCertifications;
        }

        public function set languages(value:ListCollectionView):void {
            _languages = value;
        }
        public function get languages():ListCollectionView {
            return _languages;
        }

        public function set person(value:String):void {
            _person = value;
        }
        public function get person():String {
            return _person;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _degrees = input.readObject() as ListCollectionView;
            _educationCertifications = input.readObject() as ListCollectionView;
            _languages = input.readObject() as ListCollectionView;
            _person = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_degrees);
            output.writeObject(_educationCertifications);
            output.writeObject(_languages);
            output.writeObject(_person);
        }
    }
}