/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (EndorsementDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import com.tps.tpi.model.objects.lite.PersonLite;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class EndorsementDtoBase extends AbstractDto {

        private var _endorsedOn:Date;
        private var _endorser:PersonLite;
        private var _stars:Number;

        public function set endorsedOn(value:Date):void {
            _endorsedOn = value;
        }
        public function get endorsedOn():Date {
            return _endorsedOn;
        }

        public function set endorser(value:PersonLite):void {
            _endorser = value;
        }
        public function get endorser():PersonLite {
            return _endorser;
        }

        public function set stars(value:Number):void {
            _stars = value;
        }
        public function get stars():Number {
            return _stars;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _endorsedOn = input.readObject() as Date;
            _endorser = input.readObject() as PersonLite;
            _stars = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_endorsedOn);
            output.writeObject(_endorser);
            output.writeObject(_stars);
        }
    }
}