/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.tps.tpi.model.objects.dto {

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.dto.LanguageDto")]
    public class LanguageDto extends LanguageDtoBase {
    }
}