/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (LanguageEndorsementDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class LanguageEndorsementDtoBase extends AbstractDto {

        private var _endorsement:EndorsementDto;
        private var _language:String;

        public function set endorsement(value:EndorsementDto):void {
            _endorsement = value;
        }
        public function get endorsement():EndorsementDto {
            return _endorsement;
        }

        public function set language(value:String):void {
            _language = value;
        }
        public function get language():String {
            return _language;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _endorsement = input.readObject() as EndorsementDto;
            _language = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_endorsement);
            output.writeObject(_language);
        }
    }
}