/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PatentDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class PatentDtoBase extends AbstractReferenceDataDto {

        private var _biography:String;

        public function set biography(value:String):void {
            _biography = value;
        }
        public function get biography():String {
            return _biography;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _biography = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_biography);
        }
    }
}