/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PersonDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class PersonDtoBase extends AbstractDto {

        private var _aim:String;
        private var _availability:Date;
        private var _currentBiographySkilledRole:BiographySkilledRoleDto;
        private var _currentDepartment:DepartmentDto;
        private var _currentEmploymentType:String;
        private var _currentLocation:CityDto;
        private var _currentSalary:Number;
        private var _disability:String;
        private var _facebook:String;
        private var _fax:String;
        private var _faxCountryCode:String;
        private var _firstName:String;
        private var _gtalk:String;
        private var _homeEmail:String;
        private var _homePhone:String;
        private var _homePhoneCountryCode:String;
        private var _homePhoneExtension:String;
        private var _interests:ListCollectionView;
        private var _lastLogin:Date;
        private var _lastName:String;
        private var _lastRecordUpdate:Date;
        private var _maritalStatus:String;
        private var _middleName:String;
        private var _mobilePhone:String;
        private var _mobilePhoneCountryCode:String;
        private var _mobilePhoneExtension:String;
        private var _msn:String;
        private var _personAddresses:ListCollectionView;
        private var _preferredEmail:String;
        private var _preferredPersonAddress:PersonAddressDto;
        private var _preferredPhone:String;
        private var _preferredPhoneCountryCode:String;
        private var _preferredPhoneExtension:String;
        private var _preferredSalary:Number;
        private var _profileImageUrl:String;
        private var _profileImageUrlLarge:String;
        private var _profileImageUrlSmall:String;
        private var _race:String;
        private var _skype:String;
        private var _status:String;
        private var _timezone:String;
        private var _twitter:String;
        private var _user:String;
        private var _workEmail:String;
        private var _workPhone:String;
        private var _workPhoneCountryCode:String;
        private var _workPhoneExtension:String;
        private var _yahoo:String;

        public function set aim(value:String):void {
            _aim = value;
        }
        public function get aim():String {
            return _aim;
        }

        public function set availability(value:Date):void {
            _availability = value;
        }
        public function get availability():Date {
            return _availability;
        }

        public function set currentBiographySkilledRole(value:BiographySkilledRoleDto):void {
            _currentBiographySkilledRole = value;
        }
        public function get currentBiographySkilledRole():BiographySkilledRoleDto {
            return _currentBiographySkilledRole;
        }

        public function set currentDepartment(value:DepartmentDto):void {
            _currentDepartment = value;
        }
        public function get currentDepartment():DepartmentDto {
            return _currentDepartment;
        }

        public function set currentEmploymentType(value:String):void {
            _currentEmploymentType = value;
        }
        public function get currentEmploymentType():String {
            return _currentEmploymentType;
        }

        public function set currentLocation(value:CityDto):void {
            _currentLocation = value;
        }
        public function get currentLocation():CityDto {
            return _currentLocation;
        }

        public function set currentSalary(value:Number):void {
            _currentSalary = value;
        }
        public function get currentSalary():Number {
            return _currentSalary;
        }

        public function set disability(value:String):void {
            _disability = value;
        }
        public function get disability():String {
            return _disability;
        }

        public function set facebook(value:String):void {
            _facebook = value;
        }
        public function get facebook():String {
            return _facebook;
        }

        public function set fax(value:String):void {
            _fax = value;
        }
        public function get fax():String {
            return _fax;
        }

        public function set faxCountryCode(value:String):void {
            _faxCountryCode = value;
        }
        public function get faxCountryCode():String {
            return _faxCountryCode;
        }

        public function set firstName(value:String):void {
            _firstName = value;
        }
        public function get firstName():String {
            return _firstName;
        }

        public function set gtalk(value:String):void {
            _gtalk = value;
        }
        public function get gtalk():String {
            return _gtalk;
        }

        public function set homeEmail(value:String):void {
            _homeEmail = value;
        }
        public function get homeEmail():String {
            return _homeEmail;
        }

        public function set homePhone(value:String):void {
            _homePhone = value;
        }
        public function get homePhone():String {
            return _homePhone;
        }

        public function set homePhoneCountryCode(value:String):void {
            _homePhoneCountryCode = value;
        }
        public function get homePhoneCountryCode():String {
            return _homePhoneCountryCode;
        }

        public function set homePhoneExtension(value:String):void {
            _homePhoneExtension = value;
        }
        public function get homePhoneExtension():String {
            return _homePhoneExtension;
        }

        public function set interests(value:ListCollectionView):void {
            _interests = value;
        }
        public function get interests():ListCollectionView {
            return _interests;
        }

        public function set lastLogin(value:Date):void {
            _lastLogin = value;
        }
        public function get lastLogin():Date {
            return _lastLogin;
        }

        public function set lastName(value:String):void {
            _lastName = value;
        }
        public function get lastName():String {
            return _lastName;
        }

        public function set lastRecordUpdate(value:Date):void {
            _lastRecordUpdate = value;
        }
        public function get lastRecordUpdate():Date {
            return _lastRecordUpdate;
        }

        public function set maritalStatus(value:String):void {
            _maritalStatus = value;
        }
        public function get maritalStatus():String {
            return _maritalStatus;
        }

        public function set middleName(value:String):void {
            _middleName = value;
        }
        public function get middleName():String {
            return _middleName;
        }

        public function set mobilePhone(value:String):void {
            _mobilePhone = value;
        }
        public function get mobilePhone():String {
            return _mobilePhone;
        }

        public function set mobilePhoneCountryCode(value:String):void {
            _mobilePhoneCountryCode = value;
        }
        public function get mobilePhoneCountryCode():String {
            return _mobilePhoneCountryCode;
        }

        public function set mobilePhoneExtension(value:String):void {
            _mobilePhoneExtension = value;
        }
        public function get mobilePhoneExtension():String {
            return _mobilePhoneExtension;
        }

        public function set msn(value:String):void {
            _msn = value;
        }
        public function get msn():String {
            return _msn;
        }

        public function set personAddresses(value:ListCollectionView):void {
            _personAddresses = value;
        }
        public function get personAddresses():ListCollectionView {
            return _personAddresses;
        }

        public function set preferredEmail(value:String):void {
            _preferredEmail = value;
        }
        public function get preferredEmail():String {
            return _preferredEmail;
        }

        public function set preferredPersonAddress(value:PersonAddressDto):void {
            _preferredPersonAddress = value;
        }
        public function get preferredPersonAddress():PersonAddressDto {
            return _preferredPersonAddress;
        }

        public function set preferredPhone(value:String):void {
            _preferredPhone = value;
        }
        public function get preferredPhone():String {
            return _preferredPhone;
        }

        public function set preferredPhoneCountryCode(value:String):void {
            _preferredPhoneCountryCode = value;
        }
        public function get preferredPhoneCountryCode():String {
            return _preferredPhoneCountryCode;
        }

        public function set preferredPhoneExtension(value:String):void {
            _preferredPhoneExtension = value;
        }
        public function get preferredPhoneExtension():String {
            return _preferredPhoneExtension;
        }

        public function set preferredSalary(value:Number):void {
            _preferredSalary = value;
        }
        public function get preferredSalary():Number {
            return _preferredSalary;
        }

        public function set profileImageUrl(value:String):void {
            _profileImageUrl = value;
        }
        public function get profileImageUrl():String {
            return _profileImageUrl;
        }

        public function set profileImageUrlLarge(value:String):void {
            _profileImageUrlLarge = value;
        }
        public function get profileImageUrlLarge():String {
            return _profileImageUrlLarge;
        }

        public function set profileImageUrlSmall(value:String):void {
            _profileImageUrlSmall = value;
        }
        public function get profileImageUrlSmall():String {
            return _profileImageUrlSmall;
        }

        public function set race(value:String):void {
            _race = value;
        }
        public function get race():String {
            return _race;
        }

        public function set skype(value:String):void {
            _skype = value;
        }
        public function get skype():String {
            return _skype;
        }

        public function set status(value:String):void {
            _status = value;
        }
        public function get status():String {
            return _status;
        }

        public function set timezone(value:String):void {
            _timezone = value;
        }
        public function get timezone():String {
            return _timezone;
        }

        public function set twitter(value:String):void {
            _twitter = value;
        }
        public function get twitter():String {
            return _twitter;
        }

        public function set user(value:String):void {
            _user = value;
        }
        public function get user():String {
            return _user;
        }

        public function set workEmail(value:String):void {
            _workEmail = value;
        }
        public function get workEmail():String {
            return _workEmail;
        }

        public function set workPhone(value:String):void {
            _workPhone = value;
        }
        public function get workPhone():String {
            return _workPhone;
        }

        public function set workPhoneCountryCode(value:String):void {
            _workPhoneCountryCode = value;
        }
        public function get workPhoneCountryCode():String {
            return _workPhoneCountryCode;
        }

        public function set workPhoneExtension(value:String):void {
            _workPhoneExtension = value;
        }
        public function get workPhoneExtension():String {
            return _workPhoneExtension;
        }

        public function set yahoo(value:String):void {
            _yahoo = value;
        }
        public function get yahoo():String {
            return _yahoo;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _aim = input.readObject() as String;
            _availability = input.readObject() as Date;
            _currentBiographySkilledRole = input.readObject() as BiographySkilledRoleDto;
            _currentDepartment = input.readObject() as DepartmentDto;
            _currentEmploymentType = input.readObject() as String;
            _currentLocation = input.readObject() as CityDto;
            _currentSalary = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _disability = input.readObject() as String;
            _facebook = input.readObject() as String;
            _fax = input.readObject() as String;
            _faxCountryCode = input.readObject() as String;
            _firstName = input.readObject() as String;
            _gtalk = input.readObject() as String;
            _homeEmail = input.readObject() as String;
            _homePhone = input.readObject() as String;
            _homePhoneCountryCode = input.readObject() as String;
            _homePhoneExtension = input.readObject() as String;
            _interests = input.readObject() as ListCollectionView;
            _lastLogin = input.readObject() as Date;
            _lastName = input.readObject() as String;
            _lastRecordUpdate = input.readObject() as Date;
            _maritalStatus = input.readObject() as String;
            _middleName = input.readObject() as String;
            _mobilePhone = input.readObject() as String;
            _mobilePhoneCountryCode = input.readObject() as String;
            _mobilePhoneExtension = input.readObject() as String;
            _msn = input.readObject() as String;
            _personAddresses = input.readObject() as ListCollectionView;
            _preferredEmail = input.readObject() as String;
            _preferredPersonAddress = input.readObject() as PersonAddressDto;
            _preferredPhone = input.readObject() as String;
            _preferredPhoneCountryCode = input.readObject() as String;
            _preferredPhoneExtension = input.readObject() as String;
            _preferredSalary = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _profileImageUrl = input.readObject() as String;
            _profileImageUrlLarge = input.readObject() as String;
            _profileImageUrlSmall = input.readObject() as String;
            _race = input.readObject() as String;
            _skype = input.readObject() as String;
            _status = input.readObject() as String;
            _timezone = input.readObject() as String;
            _twitter = input.readObject() as String;
            _user = input.readObject() as String;
            _workEmail = input.readObject() as String;
            _workPhone = input.readObject() as String;
            _workPhoneCountryCode = input.readObject() as String;
            _workPhoneExtension = input.readObject() as String;
            _yahoo = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_aim);
            output.writeObject(_availability);
            output.writeObject(_currentBiographySkilledRole);
            output.writeObject(_currentDepartment);
            output.writeObject(_currentEmploymentType);
            output.writeObject(_currentLocation);
            output.writeObject(_currentSalary);
            output.writeObject(_disability);
            output.writeObject(_facebook);
            output.writeObject(_fax);
            output.writeObject(_faxCountryCode);
            output.writeObject(_firstName);
            output.writeObject(_gtalk);
            output.writeObject(_homeEmail);
            output.writeObject(_homePhone);
            output.writeObject(_homePhoneCountryCode);
            output.writeObject(_homePhoneExtension);
            output.writeObject(_interests);
            output.writeObject(_lastLogin);
            output.writeObject(_lastName);
            output.writeObject(_lastRecordUpdate);
            output.writeObject(_maritalStatus);
            output.writeObject(_middleName);
            output.writeObject(_mobilePhone);
            output.writeObject(_mobilePhoneCountryCode);
            output.writeObject(_mobilePhoneExtension);
            output.writeObject(_msn);
            output.writeObject(_personAddresses);
            output.writeObject(_preferredEmail);
            output.writeObject(_preferredPersonAddress);
            output.writeObject(_preferredPhone);
            output.writeObject(_preferredPhoneCountryCode);
            output.writeObject(_preferredPhoneExtension);
            output.writeObject(_preferredSalary);
            output.writeObject(_profileImageUrl);
            output.writeObject(_profileImageUrlLarge);
            output.writeObject(_profileImageUrlSmall);
            output.writeObject(_race);
            output.writeObject(_skype);
            output.writeObject(_status);
            output.writeObject(_timezone);
            output.writeObject(_twitter);
            output.writeObject(_user);
            output.writeObject(_workEmail);
            output.writeObject(_workPhone);
            output.writeObject(_workPhoneCountryCode);
            output.writeObject(_workPhoneExtension);
            output.writeObject(_yahoo);
        }
    }
}