/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PositionDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class PositionDtoBase extends AbstractDto {

        private var _city:String;
        private var _cityName:String;
        private var _companyName:String;
        private var _department:String;
        private var _departmentName:String;
        private var _from:Date;
        private var _history:String;
        private var _positionEndorsements:ListCollectionView;
        private var _skilledRole:SkilledRoleDto;
        private var _to:Date;
        private var _type:String;

        public function set city(value:String):void {
            _city = value;
        }
        public function get city():String {
            return _city;
        }

        public function set cityName(value:String):void {
            _cityName = value;
        }
        public function get cityName():String {
            return _cityName;
        }

        public function set companyName(value:String):void {
            _companyName = value;
        }
        public function get companyName():String {
            return _companyName;
        }

        public function set department(value:String):void {
            _department = value;
        }
        public function get department():String {
            return _department;
        }

        public function set departmentName(value:String):void {
            _departmentName = value;
        }
        public function get departmentName():String {
            return _departmentName;
        }

        public function set from(value:Date):void {
            _from = value;
        }
        public function get from():Date {
            return _from;
        }

        public function set history(value:String):void {
            _history = value;
        }
        public function get history():String {
            return _history;
        }

        public function set positionEndorsements(value:ListCollectionView):void {
            _positionEndorsements = value;
        }
        public function get positionEndorsements():ListCollectionView {
            return _positionEndorsements;
        }

        public function set skilledRole(value:SkilledRoleDto):void {
            _skilledRole = value;
        }
        public function get skilledRole():SkilledRoleDto {
            return _skilledRole;
        }

        public function set to(value:Date):void {
            _to = value;
        }
        public function get to():Date {
            return _to;
        }

        public function set type(value:String):void {
            _type = value;
        }
        public function get type():String {
            return _type;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _city = input.readObject() as String;
            _cityName = input.readObject() as String;
            _companyName = input.readObject() as String;
            _department = input.readObject() as String;
            _departmentName = input.readObject() as String;
            _from = input.readObject() as Date;
            _history = input.readObject() as String;
            _positionEndorsements = input.readObject() as ListCollectionView;
            _skilledRole = input.readObject() as SkilledRoleDto;
            _to = input.readObject() as Date;
            _type = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_city);
            output.writeObject(_cityName);
            output.writeObject(_companyName);
            output.writeObject(_department);
            output.writeObject(_departmentName);
            output.writeObject(_from);
            output.writeObject(_history);
            output.writeObject(_positionEndorsements);
            output.writeObject(_skilledRole);
            output.writeObject(_to);
            output.writeObject(_type);
        }
    }
}