/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PrincipalData.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class PrincipalDataBase implements IExternalizable {

        private var _roles:Array;
        private var _username:String;

        public function set roles(value:Array):void {
            _roles = value;
        }
        public function get roles():Array {
            return _roles;
        }

        public function set username(value:String):void {
            _username = value;
        }
        public function get username():String {
            return _username;
        }

        public function readExternal(input:IDataInput):void {
            _roles = input.readObject() as Array;
            _username = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_roles);
            output.writeObject(_username);
        }
    }
}