/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (ProjectDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class ProjectDtoBase extends AbstractDto {

        private var _city:CityDto;
        private var _company:CompanyDto;
        private var _from:Date;
        private var _history:String;
        private var _name:String;
        private var _projectEndorsements:ListCollectionView;
        private var _skilledRole:SkilledRoleDto;
        private var _to:Date;

        public function set city(value:CityDto):void {
            _city = value;
        }
        public function get city():CityDto {
            return _city;
        }

        public function set company(value:CompanyDto):void {
            _company = value;
        }
        public function get company():CompanyDto {
            return _company;
        }

        public function set from(value:Date):void {
            _from = value;
        }
        public function get from():Date {
            return _from;
        }

        public function set history(value:String):void {
            _history = value;
        }
        public function get history():String {
            return _history;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set projectEndorsements(value:ListCollectionView):void {
            _projectEndorsements = value;
        }
        public function get projectEndorsements():ListCollectionView {
            return _projectEndorsements;
        }

        public function set skilledRole(value:SkilledRoleDto):void {
            _skilledRole = value;
        }
        public function get skilledRole():SkilledRoleDto {
            return _skilledRole;
        }

        public function set to(value:Date):void {
            _to = value;
        }
        public function get to():Date {
            return _to;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _city = input.readObject() as CityDto;
            _company = input.readObject() as CompanyDto;
            _from = input.readObject() as Date;
            _history = input.readObject() as String;
            _name = input.readObject() as String;
            _projectEndorsements = input.readObject() as ListCollectionView;
            _skilledRole = input.readObject() as SkilledRoleDto;
            _to = input.readObject() as Date;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_city);
            output.writeObject(_company);
            output.writeObject(_from);
            output.writeObject(_history);
            output.writeObject(_name);
            output.writeObject(_projectEndorsements);
            output.writeObject(_skilledRole);
            output.writeObject(_to);
        }
    }
}