/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PublicationDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class PublicationDtoBase extends AbstractReferenceDataDto {

        private var _biography:String;
        private var _issueDate:Date;
        private var _type:String;

        public function set biography(value:String):void {
            _biography = value;
        }
        public function get biography():String {
            return _biography;
        }

        public function set issueDate(value:Date):void {
            _issueDate = value;
        }
        public function get issueDate():Date {
            return _issueDate;
        }

        public function set type(value:String):void {
            _type = value;
        }
        public function get type():String {
            return _type;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _biography = input.readObject() as String;
            _issueDate = input.readObject() as Date;
            _type = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_biography);
            output.writeObject(_issueDate);
            output.writeObject(_type);
        }
    }
}