/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SearchComponentDto.as).
 */

/**
 * 
 * overwritten by DK...removed IMap use 
 *
 **/

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    

    [Bindable]
    public class SearchComponentDtoBase extends AbstractDto {

        private var _searchMap:Object;

        public function set searchMap(value:Object):void {
            _searchMap = value;
        }
        public function get searchMap():Object {
            return _searchMap;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _searchMap = input.readObject() as Object;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_searchMap);
        }
    }
}