/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SearchDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ArrayCollection;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class SearchDtoBase extends AbstractDto {

        private var _company:String;
        private var _groups:ArrayCollection;
        private var _hitCount:Number;
        private var _name:String;
        private var _persons:ListCollectionView;
        private var _user:String;

        public function set company(value:String):void {
            _company = value;
        }
        public function get company():String {
            return _company;
        }

        public function set groups(value:ArrayCollection):void {
            _groups = value;
        }
        public function get groups():ArrayCollection {
            return _groups;
        }

        public function set hitCount(value:Number):void {
            _hitCount = value;
        }
        public function get hitCount():Number {
            return _hitCount;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set persons(value:ListCollectionView):void {
            _persons = value;
        }
        public function get persons():ListCollectionView {
            return _persons;
        }

        public function set user(value:String):void {
            _user = value;
        }
        public function get user():String {
            return _user;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _company = input.readObject() as String;
            _groups = input.readObject() as ArrayCollection;
            _hitCount = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _name = input.readObject() as String;
            _persons = input.readObject() as ListCollectionView;
            _user = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_company);
            output.writeObject(_groups);
            output.writeObject(_hitCount);
            output.writeObject(_name);
            output.writeObject(_persons);
            output.writeObject(_user);
        }
    }
}