/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SearchComponentGroupDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ArrayCollection;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class SearchComponentGroupDtoBase extends AbstractDto {

        private var _components:ArrayCollection;
        private var _search:String;
        private var _type:String;

        public function set components(value:ArrayCollection):void {
            _components = value;
        }
        public function get components():ArrayCollection {
            return _components;
        }

        public function set search(value:String):void {
            _search = value;
        }
        public function get search():String {
            return _search;
        }

        public function set type(value:String):void {
            _type = value;
        }
        public function get type():String {
            return _type;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _components = input.readObject() as ArrayCollection;
            _search = input.readObject() as String;
            _type = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_components);
            output.writeObject(_search);
            output.writeObject(_type);
        }
    }
}