/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (SkillDto.as).
 */

package com.tps.tpi.model.objects.dto {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class SkillDtoBase extends AbstractReferenceDataDto {

        private var _parent:String;

        public function set parent(value:String):void {
            _parent = value;
        }
        public function get parent():String {
            return _parent;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _parent = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_parent);
        }
    }
}