/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.AddressTypeCd")]
    public class AddressTypeCd extends Enum {

        public static const HOME:AddressTypeCd = new AddressTypeCd("HOME", _);
        public static const WORK:AddressTypeCd = new AddressTypeCd("WORK", _);
        public static const VACATION:AddressTypeCd = new AddressTypeCd("VACATION", _);

        function AddressTypeCd(value:String = null, restrictor:* = null) {
            super((value || HOME.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [HOME, WORK, VACATION];
        }

        public static function valueOf(name:String):AddressTypeCd {
            return AddressTypeCd(HOME.constantOf(name));
        }
    }
}