/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.BooleanTypeCd")]
    public class BooleanTypeCd extends Enum {

        public static const TRUE:BooleanTypeCd = new BooleanTypeCd("TRUE", _);
        public static const FALSE:BooleanTypeCd = new BooleanTypeCd("FALSE", _);
        public static const MAYBE:BooleanTypeCd = new BooleanTypeCd("MAYBE", _);

        function BooleanTypeCd(value:String = null, restrictor:* = null) {
            super((value || TRUE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [TRUE, FALSE, MAYBE];
        }

        public static function valueOf(name:String):BooleanTypeCd {
            return BooleanTypeCd(TRUE.constantOf(name));
        }
    }
}