/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.CoverageTypeCd")]
    public class CoverageTypeCd extends Enum {

        public static const CLIENT:CoverageTypeCd = new CoverageTypeCd("CLIENT", _);
        public static const ROLE:CoverageTypeCd = new CoverageTypeCd("ROLE", _);
        public static const PRODUCT:CoverageTypeCd = new CoverageTypeCd("PRODUCT", _);
        public static const TERRITORY:CoverageTypeCd = new CoverageTypeCd("TERRITORY", _);

        function CoverageTypeCd(value:String = null, restrictor:* = null) {
            super((value || CLIENT.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [CLIENT, ROLE, PRODUCT, TERRITORY];
        }

        public static function valueOf(name:String):CoverageTypeCd {
            return CoverageTypeCd(CLIENT.constantOf(name));
        }
    }
}