/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.DegreeTypeCd")]
    public class DegreeTypeCd extends Enum {

        public static const BS:DegreeTypeCd = new DegreeTypeCd("BS", _);
        public static const MS:DegreeTypeCd = new DegreeTypeCd("MS", _);
        public static const BA:DegreeTypeCd = new DegreeTypeCd("BA", _);
        public static const MA:DegreeTypeCd = new DegreeTypeCd("MA", _);
        public static const MBA:DegreeTypeCd = new DegreeTypeCd("MBA", _);
        public static const BBS:DegreeTypeCd = new DegreeTypeCd("BBS", _);
        public static const BBA:DegreeTypeCd = new DegreeTypeCd("BBA", _);
        public static const DP:DegreeTypeCd = new DegreeTypeCd("DP", _);
        public static const DS:DegreeTypeCd = new DegreeTypeCd("DS", _);
        public static const DJ:DegreeTypeCd = new DegreeTypeCd("DJ", _);
        public static const DM:DegreeTypeCd = new DegreeTypeCd("DM", _);
        public static const ASC:DegreeTypeCd = new DegreeTypeCd("ASC", _);
        public static const JD:DegreeTypeCd = new DegreeTypeCd("JD", _);
        public static const PHD:DegreeTypeCd = new DegreeTypeCd("PHD", _);

        function DegreeTypeCd(value:String = null, restrictor:* = null) {
            super((value || BS.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [BS, MS, BA, MA, MBA, BBS, BBA, DP, DS, DJ, DM, ASC, JD, PHD];
        }

        public static function valueOf(name:String):DegreeTypeCd {
            return DegreeTypeCd(BS.constantOf(name));
        }
    }
}