/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.EmploymentTypeCd")]
    public class EmploymentTypeCd extends Enum {

        public static const CONSULTANT:EmploymentTypeCd = new EmploymentTypeCd("CONSULTANT", _);
        public static const ADVISOR:EmploymentTypeCd = new EmploymentTypeCd("ADVISOR", _);
        public static const CONTRACTOR:EmploymentTypeCd = new EmploymentTypeCd("CONTRACTOR", _);
        public static const EMPLOYEE:EmploymentTypeCd = new EmploymentTypeCd("EMPLOYEE", _);
        public static const GTE:EmploymentTypeCd = new EmploymentTypeCd("GTE", _);
        public static const VENDOR:EmploymentTypeCd = new EmploymentTypeCd("VENDOR", _);

        function EmploymentTypeCd(value:String = null, restrictor:* = null) {
            super((value || CONSULTANT.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [CONSULTANT, ADVISOR, CONTRACTOR, EMPLOYEE, GTE, VENDOR];
        }

        public static function valueOf(name:String):EmploymentTypeCd {
            return EmploymentTypeCd(CONSULTANT.constantOf(name));
        }
    }
}