/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.EndorsementTypeCd")]
    public class EndorsementTypeCd extends Enum {

        public static const COVERAGE:EndorsementTypeCd = new EndorsementTypeCd("COVERAGE", _);
        public static const LANGUAGE:EndorsementTypeCd = new EndorsementTypeCd("LANGUAGE", _);
        public static const POSITION:EndorsementTypeCd = new EndorsementTypeCd("POSITION", _);
        public static const PROJECT:EndorsementTypeCd = new EndorsementTypeCd("PROJECT", _);
        public static const SKILL:EndorsementTypeCd = new EndorsementTypeCd("SKILL", _);

        function EndorsementTypeCd(value:String = null, restrictor:* = null) {
            super((value || COVERAGE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [COVERAGE, LANGUAGE, POSITION, PROJECT, SKILL];
        }

        public static function valueOf(name:String):EndorsementTypeCd {
            return EndorsementTypeCd(COVERAGE.constantOf(name));
        }
    }
}