/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.EntitlementTypeCd")]
    public class EntitlementTypeCd extends Enum {

        public static const ENTERPRISE:EntitlementTypeCd = new EntitlementTypeCd("ENTERPRISE", _);
        public static const PERSON:EntitlementTypeCd = new EntitlementTypeCd("PERSON", _);

        function EntitlementTypeCd(value:String = null, restrictor:* = null) {
            super((value || ENTERPRISE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ENTERPRISE, PERSON];
        }

        public static function valueOf(name:String):EntitlementTypeCd {
            return EntitlementTypeCd(ENTERPRISE.constantOf(name));
        }
    }
}