/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.LanguageLevelCd")]
    public class LanguageLevelCd extends Enum {

        public static const NATIVE:LanguageLevelCd = new LanguageLevelCd("NATIVE", _);
        public static const FLUENT:LanguageLevelCd = new LanguageLevelCd("FLUENT", _);
        public static const INTERMEDIATE:LanguageLevelCd = new LanguageLevelCd("INTERMEDIATE", _);
        public static const BASIC:LanguageLevelCd = new LanguageLevelCd("BASIC", _);

        function LanguageLevelCd(value:String = null, restrictor:* = null) {
            super((value || NATIVE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [NATIVE, FLUENT, INTERMEDIATE, BASIC];
        }

        public static function valueOf(name:String):LanguageLevelCd {
            return LanguageLevelCd(NATIVE.constantOf(name));
        }
    }
}