/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.MajorTypeCd")]
    public class MajorTypeCd extends Enum {

        public static const COMPUTER_SCIENCE:MajorTypeCd = new MajorTypeCd("COMPUTER_SCIENCE", _);
        public static const ECONOMICS:MajorTypeCd = new MajorTypeCd("ECONOMICS", _);
        public static const MATH:MajorTypeCd = new MajorTypeCd("MATH", _);
        public static const FINANCE:MajorTypeCd = new MajorTypeCd("FINANCE", _);
        public static const ENGINEERING:MajorTypeCd = new MajorTypeCd("ENGINEERING", _);
        public static const INTERNATIONAL_LAW:MajorTypeCd = new MajorTypeCd("INTERNATIONAL_LAW", _);
        public static const FOREIGN_STUDIES:MajorTypeCd = new MajorTypeCd("FOREIGN_STUDIES", _);
        public static const MATHEMATICS:MajorTypeCd = new MajorTypeCd("MATHEMATICS", _);
        public static const BUSINESS_MANAGEMENT:MajorTypeCd = new MajorTypeCd("BUSINESS_MANAGEMENT", _);
        public static const PROJECT_ENGINEERING:MajorTypeCd = new MajorTypeCd("PROJECT_ENGINEERING", _);
        public static const COMMUNICATION:MajorTypeCd = new MajorTypeCd("COMMUNICATION", _);
        public static const PATENT_LAW:MajorTypeCd = new MajorTypeCd("PATENT_LAW", _);
        public static const INTELLECTUAL_PROPERTY_LAW:MajorTypeCd = new MajorTypeCd("INTELLECTUAL_PROPERTY_LAW", _);
        public static const ADVANCED_STUDIES:MajorTypeCd = new MajorTypeCd("ADVANCED_STUDIES", _);

        function MajorTypeCd(value:String = null, restrictor:* = null) {
            super((value || COMPUTER_SCIENCE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [COMPUTER_SCIENCE, ECONOMICS, MATH, FINANCE, ENGINEERING, INTERNATIONAL_LAW, FOREIGN_STUDIES, MATHEMATICS, BUSINESS_MANAGEMENT, PROJECT_ENGINEERING, COMMUNICATION, PATENT_LAW, INTELLECTUAL_PROPERTY_LAW, ADVANCED_STUDIES];
        }

        public static function valueOf(name:String):MajorTypeCd {
            return MajorTypeCd(COMPUTER_SCIENCE.constantOf(name));
        }
    }
}