/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.MaritalStatusCd")]
    public class MaritalStatusCd extends Enum {

        public static const SINGLE:MaritalStatusCd = new MaritalStatusCd("SINGLE", _);
        public static const MARRIED:MaritalStatusCd = new MaritalStatusCd("MARRIED", _);
        public static const WIDOWED:MaritalStatusCd = new MaritalStatusCd("WIDOWED", _);
        public static const PARTNERSHIP:MaritalStatusCd = new MaritalStatusCd("PARTNERSHIP", _);

        function MaritalStatusCd(value:String = null, restrictor:* = null) {
            super((value || SINGLE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [SINGLE, MARRIED, WIDOWED, PARTNERSHIP];
        }

        public static function valueOf(name:String):MaritalStatusCd {
            return MaritalStatusCd(SINGLE.constantOf(name));
        }
    }
}