/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.OnlineTypeCd")]
    public class OnlineTypeCd extends Enum {

        public static const EMAIL:OnlineTypeCd = new OnlineTypeCd("EMAIL", _);
        public static const WEBSITE:OnlineTypeCd = new OnlineTypeCd("WEBSITE", _);
        public static const TWITTER:OnlineTypeCd = new OnlineTypeCd("TWITTER", _);
        public static const SKYPE:OnlineTypeCd = new OnlineTypeCd("SKYPE", _);
        public static const AIM:OnlineTypeCd = new OnlineTypeCd("AIM", _);
        public static const YAHOO:OnlineTypeCd = new OnlineTypeCd("YAHOO", _);
        public static const MSN:OnlineTypeCd = new OnlineTypeCd("MSN", _);
        public static const GTALK:OnlineTypeCd = new OnlineTypeCd("GTALK", _);
        public static const GADUGADU:OnlineTypeCd = new OnlineTypeCd("GADUGADU", _);
        public static const JABBER:OnlineTypeCd = new OnlineTypeCd("JABBER", _);
        public static const ICQ:OnlineTypeCd = new OnlineTypeCd("ICQ", _);
        public static const LOTUS:OnlineTypeCd = new OnlineTypeCd("LOTUS", _);
        public static const BONJOUR:OnlineTypeCd = new OnlineTypeCd("BONJOUR", _);
        public static const FACEBOOK:OnlineTypeCd = new OnlineTypeCd("FACEBOOK", _);
        public static const MYSPACE:OnlineTypeCd = new OnlineTypeCd("MYSPACE", _);
        public static const ZEPHYR:OnlineTypeCd = new OnlineTypeCd("ZEPHYR", _);
        public static const NOVELL:OnlineTypeCd = new OnlineTypeCd("NOVELL", _);
        public static const QQ:OnlineTypeCd = new OnlineTypeCd("QQ", _);

        function OnlineTypeCd(value:String = null, restrictor:* = null) {
            super((value || EMAIL.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [EMAIL, WEBSITE, TWITTER, SKYPE, AIM, YAHOO, MSN, GTALK, GADUGADU, JABBER, ICQ, LOTUS, BONJOUR, FACEBOOK, MYSPACE, ZEPHYR, NOVELL, QQ];
        }

        public static function valueOf(name:String):OnlineTypeCd {
            return OnlineTypeCd(EMAIL.constantOf(name));
        }
    }
}