/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.PersonStatusCd")]
    public class PersonStatusCd extends Enum {

        public static const ACTIVE:PersonStatusCd = new PersonStatusCd("ACTIVE", _);
        public static const REGISTERED:PersonStatusCd = new PersonStatusCd("REGISTERED", _);
        public static const INACTIVE:PersonStatusCd = new PersonStatusCd("INACTIVE", _);
        public static const DELETED:PersonStatusCd = new PersonStatusCd("DELETED", _);
        public static const LOCKED:PersonStatusCd = new PersonStatusCd("LOCKED", _);

        function PersonStatusCd(value:String = null, restrictor:* = null) {
            super((value || ACTIVE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ACTIVE, REGISTERED, INACTIVE, DELETED, LOCKED];
        }

        public static function valueOf(name:String):PersonStatusCd {
            return PersonStatusCd(ACTIVE.constantOf(name));
        }
    }
}