/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.PositionRoleTypeCd")]
    public class PositionRoleTypeCd extends Enum {

        public static const TITLE:PositionRoleTypeCd = new PositionRoleTypeCd("TITLE", _);
        public static const ROLE:PositionRoleTypeCd = new PositionRoleTypeCd("ROLE", _);

        function PositionRoleTypeCd(value:String = null, restrictor:* = null) {
            super((value || TITLE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [TITLE, ROLE];
        }

        public static function valueOf(name:String):PositionRoleTypeCd {
            return PositionRoleTypeCd(TITLE.constantOf(name));
        }
    }
}