/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.PublicationTypeCd")]
    public class PublicationTypeCd extends Enum {

        public static const AUDIOBOOK:PublicationTypeCd = new PublicationTypeCd("AUDIOBOOK", _);
        public static const EBOOK:PublicationTypeCd = new PublicationTypeCd("EBOOK", _);
        public static const ARTICLE:PublicationTypeCd = new PublicationTypeCd("ARTICLE", _);
        public static const BOOK:PublicationTypeCd = new PublicationTypeCd("BOOK", _);
        public static const BLOG:PublicationTypeCd = new PublicationTypeCd("BLOG", _);
        public static const REVIEW:PublicationTypeCd = new PublicationTypeCd("REVIEW", _);
        public static const PAPER:PublicationTypeCd = new PublicationTypeCd("PAPER", _);
        public static const GUIDE:PublicationTypeCd = new PublicationTypeCd("GUIDE", _);
        public static const DISSERTATION:PublicationTypeCd = new PublicationTypeCd("DISSERTATION", _);
        public static const REPORT:PublicationTypeCd = new PublicationTypeCd("REPORT", _);
        public static const OTHER:PublicationTypeCd = new PublicationTypeCd("OTHER", _);

        function PublicationTypeCd(value:String = null, restrictor:* = null) {
            super((value || AUDIOBOOK.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [AUDIOBOOK, EBOOK, ARTICLE, BOOK, BLOG, REVIEW, PAPER, GUIDE, DISSERTATION, REPORT, OTHER];
        }

        public static function valueOf(name:String):PublicationTypeCd {
            return PublicationTypeCd(AUDIOBOOK.constantOf(name));
        }
    }
}