/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.RaceCd")]
    public class RaceCd extends Enum {

        public static const ABORIGINAL:RaceCd = new RaceCd("ABORIGINAL", _);
        public static const AFRICAN:RaceCd = new RaceCd("AFRICAN", _);
        public static const ASIAN:RaceCd = new RaceCd("ASIAN", _);
        public static const CAUCASIAN:RaceCd = new RaceCd("CAUCASIAN", _);
        public static const EUROPEAN:RaceCd = new RaceCd("EUROPEAN", _);
        public static const HISPANIC:RaceCd = new RaceCd("HISPANIC", _);
        public static const INDIAN:RaceCd = new RaceCd("INDIAN", _);
        public static const MAURI:RaceCd = new RaceCd("MAURI", _);
        public static const NATIVE_AMERICAN:RaceCd = new RaceCd("NATIVE_AMERICAN", _);

        function RaceCd(value:String = null, restrictor:* = null) {
            super((value || ABORIGINAL.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ABORIGINAL, AFRICAN, ASIAN, CAUCASIAN, EUROPEAN, HISPANIC, INDIAN, MAURI, NATIVE_AMERICAN];
        }

        public static function valueOf(name:String):RaceCd {
            return RaceCd(ABORIGINAL.constantOf(name));
        }
    }
}