/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.RecordStatusTypeCd")]
    public class RecordStatusTypeCd extends Enum {

        public static const ACTIVE:RecordStatusTypeCd = new RecordStatusTypeCd("ACTIVE", _);
        public static const DELETED:RecordStatusTypeCd = new RecordStatusTypeCd("DELETED", _);

        function RecordStatusTypeCd(value:String = null, restrictor:* = null) {
            super((value || ACTIVE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ACTIVE, DELETED];
        }

        public static function valueOf(name:String):RecordStatusTypeCd {
            return RecordStatusTypeCd(ACTIVE.constantOf(name));
        }
    }
}