/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.SearchComponentFieldNameCd")]
    public class SearchComponentFieldNameCd extends Enum {

        public static const GLOBAL_EXACT_MATCH:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("GLOBAL_EXACT_MATCH", _);
        public static const GLOBAL_EXCLUDE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("GLOBAL_EXCLUDE", _);
        public static const QUICKSEARCH_KEYWORDS:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("QUICKSEARCH_KEYWORDS", _);
        public static const NAME_FIRST_NAME:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("NAME_FIRST_NAME", _);
        public static const NAME_LAST_NAME:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("NAME_LAST_NAME", _);
        public static const NAME_MIDDLE_NAME:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("NAME_MIDDLE_NAME", _);
        public static const POSITION_ROLE_TYPE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("POSITION_ROLE_TYPE", _);
        public static const POSITION_ROLE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("POSITION_ROLE", _);
        public static const LOCATION_ADDRESS:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("LOCATION_ADDRESS", _);
        public static const LOCATION_CITY:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("LOCATION_CITY", _);
        public static const LOCATION_STATE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("LOCATION_STATE", _);
        public static const LOCATION_COUNTRY:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("LOCATION_COUNTRY", _);
        public static const LOCATION_TIMEZONE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("LOCATION_TIMEZONE", _);
        public static const SKILL_EXPERTISE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("SKILL_EXPERTISE", _);
        public static const SKILL_PROFICIENCY:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("SKILL_PROFICIENCY", _);
        public static const LANGUAGE_TYPE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("LANGUAGE_TYPE", _);
        public static const LANGUAGE_VERBAL:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("LANGUAGE_VERBAL", _);
        public static const LANGUAGE_READWRITE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("LANGUAGE_READWRITE", _);
        public static const EMAIL_USERNAME:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("EMAIL_USERNAME", _);
        public static const EMAIL_DOMAIN:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("EMAIL_DOMAIN", _);
        public static const PHONE_COUNTRYCODE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PHONE_COUNTRYCODE", _);
        public static const PHONE_NUMBER:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PHONE_NUMBER", _);
        public static const PHONE_EXTENSION:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PHONE_EXTENSION", _);
        public static const EDUCATION_SCHOOL:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("EDUCATION_SCHOOL", _);
        public static const EDUCATION_DEGREE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("EDUCATION_DEGREE", _);
        public static const EDUCATION_MAJOR:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("EDUCATION_MAJOR", _);
        public static const COMPANY_COMPANY:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("COMPANY_COMPANY", _);
        public static const COMPANY_INDUSTRY:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("COMPANY_INDUSTRY", _);
        public static const PROJECT_SKILLED_ROLE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PROJECT_SKILLED_ROLE", _);
        public static const PROJECT_NAME:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PROJECT_NAME", _);
        public static const PROJECT_COMPANY_NAME:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PROJECT_COMPANY_NAME", _);
        public static const EMPLOYMENT_TYPE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("EMPLOYMENT_TYPE", _);
        public static const COVERAGE_TYPE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("COVERAGE_TYPE", _);
        public static const COVERAGE_VALUE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("COVERAGE_VALUE", _);
        public static const COVERAGE_CURRENT_PREVIOUS:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("COVERAGE_CURRENT_PREVIOUS", _);
        public static const CERTIFICATION_TITLE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("CERTIFICATION_TITLE", _);
        public static const CERTIFICATION_ISSUED_BY:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("CERTIFICATION_ISSUED_BY", _);
        public static const CERTIFICATION_ISSUE_DATE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("CERTIFICATION_ISSUE_DATE", _);
        public static const ORGANIZATION_NAME:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("ORGANIZATION_NAME", _);
        public static const ORGANIZATION_ROLE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("ORGANIZATION_ROLE", _);
        public static const INTEREST:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("INTEREST", _);
        public static const AWARD_NAME:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("AWARD_NAME", _);
        public static const AWARD_ISSUER:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("AWARD_ISSUER", _);
        public static const AWARD_ISSUE_DATE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("AWARD_ISSUE_DATE", _);
        public static const PUBLICATION_TITLE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PUBLICATION_TITLE", _);
        public static const PUBLICATION_TYPE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PUBLICATION_TYPE", _);
        public static const PATENT_CODE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PATENT_CODE", _);
        public static const PATENT_NAME:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("PATENT_NAME", _);
        public static const AVAILABILITY_DATE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("AVAILABILITY_DATE", _);
        public static const AVAILABILITY_TYPE:SearchComponentFieldNameCd = new SearchComponentFieldNameCd("AVAILABILITY_TYPE", _);

        function SearchComponentFieldNameCd(value:String = null, restrictor:* = null) {
            super((value || GLOBAL_EXACT_MATCH.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [GLOBAL_EXACT_MATCH, GLOBAL_EXCLUDE, QUICKSEARCH_KEYWORDS, NAME_FIRST_NAME, NAME_LAST_NAME, NAME_MIDDLE_NAME, POSITION_ROLE_TYPE, POSITION_ROLE, LOCATION_ADDRESS, LOCATION_CITY, LOCATION_STATE, LOCATION_COUNTRY, LOCATION_TIMEZONE, SKILL_EXPERTISE, SKILL_PROFICIENCY, LANGUAGE_TYPE, LANGUAGE_VERBAL, LANGUAGE_READWRITE, EMAIL_USERNAME, EMAIL_DOMAIN, PHONE_COUNTRYCODE, PHONE_NUMBER, PHONE_EXTENSION, EDUCATION_SCHOOL, EDUCATION_DEGREE, EDUCATION_MAJOR, COMPANY_COMPANY, COMPANY_INDUSTRY, PROJECT_SKILLED_ROLE, PROJECT_NAME, PROJECT_COMPANY_NAME, EMPLOYMENT_TYPE, COVERAGE_TYPE, COVERAGE_VALUE, COVERAGE_CURRENT_PREVIOUS, CERTIFICATION_TITLE, CERTIFICATION_ISSUED_BY, CERTIFICATION_ISSUE_DATE, ORGANIZATION_NAME, ORGANIZATION_ROLE, INTEREST, AWARD_NAME, AWARD_ISSUER, AWARD_ISSUE_DATE, PUBLICATION_TITLE, PUBLICATION_TYPE, PATENT_CODE, PATENT_NAME, AVAILABILITY_DATE, AVAILABILITY_TYPE];
        }

        public static function valueOf(name:String):SearchComponentFieldNameCd {
            return SearchComponentFieldNameCd(GLOBAL_EXACT_MATCH.constantOf(name));
        }
    }
}