/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.SearchComponentGroupTypeCd")]
    public class SearchComponentGroupTypeCd extends Enum {

        public static const QUICK_SEARCH:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("QUICK_SEARCH", _);
        public static const NAME:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("NAME", _);
        public static const EMAIL:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("EMAIL", _);
        public static const PHONE:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("PHONE", _);
        public static const LOCATION:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("LOCATION", _);
        public static const SKILLS_EXPERTISE:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("SKILLS_EXPERTISE", _);
        public static const COMPANY_INDUSTRY:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("COMPANY_INDUSTRY", _);
        public static const POSITION_ROLES:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("POSITION_ROLES", _);
        public static const PROJECTS:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("PROJECTS", _);
        public static const COVERAGE:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("COVERAGE", _);
        public static const AVAILABILITY:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("AVAILABILITY", _);
        public static const EMPLOYMENT_TYPE:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("EMPLOYMENT_TYPE", _);
        public static const EDUCATION:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("EDUCATION", _);
        public static const CERTIFICATION:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("CERTIFICATION", _);
        public static const LANGUAGE:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("LANGUAGE", _);
        public static const RATE:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("RATE", _);
        public static const ORGANIZATION:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("ORGANIZATION", _);
        public static const INTEREST:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("INTEREST", _);
        public static const AWARDS:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("AWARDS", _);
        public static const PUBLICATIONS:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("PUBLICATIONS", _);
        public static const PATENTS:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("PATENTS", _);
        public static const DEMOGRAPHIC:SearchComponentGroupTypeCd = new SearchComponentGroupTypeCd("DEMOGRAPHIC", _);

        function SearchComponentGroupTypeCd(value:String = null, restrictor:* = null) {
            super((value || QUICK_SEARCH.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [QUICK_SEARCH, NAME, EMAIL, PHONE, LOCATION, SKILLS_EXPERTISE, COMPANY_INDUSTRY, POSITION_ROLES, PROJECTS, COVERAGE, AVAILABILITY, EMPLOYMENT_TYPE, EDUCATION, CERTIFICATION, LANGUAGE, RATE, ORGANIZATION, INTEREST, AWARDS, PUBLICATIONS, PATENTS, DEMOGRAPHIC];
        }

        public static function valueOf(name:String):SearchComponentGroupTypeCd {
            return SearchComponentGroupTypeCd(QUICK_SEARCH.constantOf(name));
        }
    }
}