/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.SearchTypeCd")]
    public class SearchTypeCd extends Enum {

        public static const QUICK:SearchTypeCd = new SearchTypeCd("QUICK", _);
        public static const ADVANCED:SearchTypeCd = new SearchTypeCd("ADVANCED", _);

        function SearchTypeCd(value:String = null, restrictor:* = null) {
            super((value || QUICK.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [QUICK, ADVANCED];
        }

        public static function valueOf(name:String):SearchTypeCd {
            return SearchTypeCd(QUICK.constantOf(name));
        }
    }
}