/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.tps.tpi.model.objects.enums {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.tps.tpi.model.objects.enums.SourceTypeCd")]
    public class SourceTypeCd extends Enum {

        public static const COMPANY:SourceTypeCd = new SourceTypeCd("COMPANY", _);
        public static const PERSON:SourceTypeCd = new SourceTypeCd("PERSON", _);
        public static const SKILL:SourceTypeCd = new SourceTypeCd("SKILL", _);
        public static const SKILLEDROLEGROUP:SourceTypeCd = new SourceTypeCd("SKILLEDROLEGROUP", _);
        public static const SKILLEDROLE:SourceTypeCd = new SourceTypeCd("SKILLEDROLE", _);
        public static const SKILLGROUP:SourceTypeCd = new SourceTypeCd("SKILLGROUP", _);
        public static const SCHOOL:SourceTypeCd = new SourceTypeCd("SCHOOL", _);
        public static const REGION:SourceTypeCd = new SourceTypeCd("REGION", _);
        public static const COUNTRY:SourceTypeCd = new SourceTypeCd("COUNTRY", _);
        public static const CITY:SourceTypeCd = new SourceTypeCd("CITY", _);
        public static const INDUSTRYGROUP:SourceTypeCd = new SourceTypeCd("INDUSTRYGROUP", _);
        public static const INDUSTRY:SourceTypeCd = new SourceTypeCd("INDUSTRY", _);
        public static const CERTIFICATION:SourceTypeCd = new SourceTypeCd("CERTIFICATION", _);
        public static const PRODUCT:SourceTypeCd = new SourceTypeCd("PRODUCT", _);
        public static const COMPANYTITLE:SourceTypeCd = new SourceTypeCd("COMPANYTITLE", _);
        public static const DIVISION:SourceTypeCd = new SourceTypeCd("DIVISION", _);
        public static const DEPARTMENT:SourceTypeCd = new SourceTypeCd("DEPARTMENT", _);
        public static const COMPANY_INDUSTRY:SourceTypeCd = new SourceTypeCd("COMPANY_INDUSTRY", _);
        public static const TITLE:SourceTypeCd = new SourceTypeCd("TITLE", _);

        function SourceTypeCd(value:String = null, restrictor:* = null) {
            super((value || COMPANY.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [COMPANY, PERSON, SKILL, SKILLEDROLEGROUP, SKILLEDROLE, SKILLGROUP, SCHOOL, REGION, COUNTRY, CITY, INDUSTRYGROUP, INDUSTRY, CERTIFICATION, PRODUCT, COMPANYTITLE, DIVISION, DEPARTMENT, COMPANY_INDUSTRY, TITLE];
        }

        public static function valueOf(name:String):SourceTypeCd {
            return SourceTypeCd(COMPANY.constantOf(name));
        }
    }
}