/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (AbstractLite.as).
 */

package com.tps.tpi.model.objects.lite {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class AbstractLiteBase implements IExternalizable {

        private var _id:String;

        public function set id(value:String):void {
            _id = value;
        }
        public function get id():String {
            return _id;
        }

        public function readExternal(input:IDataInput):void {
            _id = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_id);
        }
    }
}