/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (BiographySkillLite.as).
 */

package com.tps.tpi.model.objects.lite {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class BiographySkillLiteBase extends AbstractLite {

        private var _averageStars:Number;
        private var _endorsements:Number;
        private var _proficiency:String;
        private var _skill:String;

        public function set averageStars(value:Number):void {
            _averageStars = value;
        }
        public function get averageStars():Number {
            return _averageStars;
        }

        public function set endorsements(value:Number):void {
            _endorsements = value;
        }
        public function get endorsements():Number {
            return _endorsements;
        }

        public function set proficiency(value:String):void {
            _proficiency = value;
        }
        public function get proficiency():String {
            return _proficiency;
        }

        public function set skill(value:String):void {
            _skill = value;
        }
        public function get skill():String {
            return _skill;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _averageStars = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _endorsements = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _proficiency = input.readObject() as String;
            _skill = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_averageStars);
            output.writeObject(_endorsements);
            output.writeObject(_proficiency);
            output.writeObject(_skill);
        }
    }
}