/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (LanguageLite.as).
 */

package com.tps.tpi.model.objects.lite {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;

    [Bindable]
    public class LanguageLiteBase extends AbstractLite {

        private var _averageStars:Number;
        private var _endorsements:Number;
        private var _readwrite:String;
        private var _type:String;
        private var _verbal:String;

        public function set averageStars(value:Number):void {
            _averageStars = value;
        }
        public function get averageStars():Number {
            return _averageStars;
        }

        public function set endorsements(value:Number):void {
            _endorsements = value;
        }
        public function get endorsements():Number {
            return _endorsements;
        }

        public function set readwrite(value:String):void {
            _readwrite = value;
        }
        public function get readwrite():String {
            return _readwrite;
        }

        public function set type(value:String):void {
            _type = value;
        }
        public function get type():String {
            return _type;
        }

        public function set verbal(value:String):void {
            _verbal = value;
        }
        public function get verbal():String {
            return _verbal;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _averageStars = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _endorsements = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _readwrite = input.readObject() as String;
            _type = input.readObject() as String;
            _verbal = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_averageStars);
            output.writeObject(_endorsements);
            output.writeObject(_readwrite);
            output.writeObject(_type);
            output.writeObject(_verbal);
        }
    }
}