/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PersonLite.as).
 */

package com.tps.tpi.model.objects.lite {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import mx.collections.ListCollectionView;

    [Bindable]
    public class PersonLiteBase extends AbstractLite {

        private var _biographySkills:ListCollectionView;
        private var _city:String;
        private var _country:String;
        private var _currentBiographySkilledRole:String;
        private var _email:String;
        private var _employmentType:String;
        private var _firstName:String;
        private var _languages:ListCollectionView;
        private var _lastName:String;
        private var _phone:String;
        private var _phoneCountryCode:String;
        private var _phoneExtension:String;
        private var _profileImageUrlSmall:String;
        private var _relevancy:Number;
        private var _state:String;
        private var _timezone:String;

        public function set biographySkills(value:ListCollectionView):void {
            _biographySkills = value;
        }
        public function get biographySkills():ListCollectionView {
            return _biographySkills;
        }

        public function set city(value:String):void {
            _city = value;
        }
        public function get city():String {
            return _city;
        }

        public function set country(value:String):void {
            _country = value;
        }
        public function get country():String {
            return _country;
        }

        public function set currentBiographySkilledRole(value:String):void {
            _currentBiographySkilledRole = value;
        }
        public function get currentBiographySkilledRole():String {
            return _currentBiographySkilledRole;
        }

        public function set email(value:String):void {
            _email = value;
        }
        public function get email():String {
            return _email;
        }

        public function set employmentType(value:String):void {
            _employmentType = value;
        }
        public function get employmentType():String {
            return _employmentType;
        }

        public function set firstName(value:String):void {
            _firstName = value;
        }
        public function get firstName():String {
            return _firstName;
        }

        public function set languages(value:ListCollectionView):void {
            _languages = value;
        }
        public function get languages():ListCollectionView {
            return _languages;
        }

        public function set lastName(value:String):void {
            _lastName = value;
        }
        public function get lastName():String {
            return _lastName;
        }

        public function set phone(value:String):void {
            _phone = value;
        }
        public function get phone():String {
            return _phone;
        }

        public function set phoneCountryCode(value:String):void {
            _phoneCountryCode = value;
        }
        public function get phoneCountryCode():String {
            return _phoneCountryCode;
        }

        public function set phoneExtension(value:String):void {
            _phoneExtension = value;
        }
        public function get phoneExtension():String {
            return _phoneExtension;
        }

        public function set profileImageUrlSmall(value:String):void {
            _profileImageUrlSmall = value;
        }
        public function get profileImageUrlSmall():String {
            return _profileImageUrlSmall;
        }

        public function set relevancy(value:Number):void {
            _relevancy = value;
        }
        public function get relevancy():Number {
            return _relevancy;
        }

        public function set state(value:String):void {
            _state = value;
        }
        public function get state():String {
            return _state;
        }

        public function set timezone(value:String):void {
            _timezone = value;
        }
        public function get timezone():String {
            return _timezone;
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            _biographySkills = input.readObject() as ListCollectionView;
            _city = input.readObject() as String;
            _country = input.readObject() as String;
            _currentBiographySkilledRole = input.readObject() as String;
            _email = input.readObject() as String;
            _employmentType = input.readObject() as String;
            _firstName = input.readObject() as String;
            _languages = input.readObject() as ListCollectionView;
            _lastName = input.readObject() as String;
            _phone = input.readObject() as String;
            _phoneCountryCode = input.readObject() as String;
            _phoneExtension = input.readObject() as String;
            _profileImageUrlSmall = input.readObject() as String;
            _relevancy = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            _state = input.readObject() as String;
            _timezone = input.readObject() as String;
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            output.writeObject(_biographySkills);
            output.writeObject(_city);
            output.writeObject(_country);
            output.writeObject(_currentBiographySkilledRole);
            output.writeObject(_email);
            output.writeObject(_employmentType);
            output.writeObject(_firstName);
            output.writeObject(_languages);
            output.writeObject(_lastName);
            output.writeObject(_phone);
            output.writeObject(_phoneCountryCode);
            output.writeObject(_phoneExtension);
            output.writeObject(_profileImageUrlSmall);
            output.writeObject(_relevancy);
            output.writeObject(_state);
            output.writeObject(_timezone);
        }
    }
}